### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Exorcism0666** [UtaUtaUtau/straycat#1]
Is there a way to solve this "Permission" problem? (I used the ".exe" because I also had problems with the ".py")

![image](https://user-images.githubusercontent.com/46537034/209433554-57778124-f122-430c-a3f2-103e24470f0e.png)

**Comment by UtaUtaUtau** [comment]
the resampler doesn't have permissions to write the feature file because the voicebank is in the C:/ folder which i think normally requires admin permissions?

for a temporary solution you could have the voicebank folder outside of the C: drive, or at least outside Program Files as i don't know how to grant a resampler permission to write in C:/Program Files right now.
